name: Build and deploy Node.js app to Azure Web App - azure-node-demo
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # or '20.x' if you prefer

      - name: Install dependencies
        run: npm install

      - name: Build project (if any)
        run: npm run build --if-present

      - name: Run tests (if any)
        run: npm run test --if-present

      - name: Zip files for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Deploy zip directly without unzipping
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'azure-node-demo-hwfgcth9fmascehd'  # Your exact Azure Web App name
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
